name: Django CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.12
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432

        # options: >-
        #   --health-cmd pg-isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: python manage.py migrate
        env: 
          DATABASE_URL: postgres://postgres:tyre321@localhost:5432/postgres
      - name: Run Tests
        run: python manage.py test
        env: 
          DATABASE_URL: postgres://postgres:tyre321@localhost:5432/postgres



